// Auto-generated by RTTR Codegen
#include "test.ecs.cpp"

void RegisterDummy() {
    rttr::registration::class_<Test::Test2>("Test::Test2")
        .property("c", &Test::Test2.c)
        .property("d", &Test::Test2.d);
    rttr::registration::class_<Test>("Test")
        .property("a", &Test.a)
        .property("b", &Test.b)
        .property("a2", &Test.a2)
        .property("z", &Test.z)
        .property("trash", &Test.trash);
}
