set( ECS_SRC
    ${CMAKE_CURRENT_LIST_DIR}/EntityId.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Index.hpp
    ${CMAKE_CURRENT_LIST_DIR}/World.hpp
    ${CMAKE_CURRENT_LIST_DIR}/World.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Archetype.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Archetype.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ArchetypeEntityIndex.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CommandBuffer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CommandBuffer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EntityStorage.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Query.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Entity.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EntityId.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EntityBuilder.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Event.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EventStorage.hpp
    ${CMAKE_CURRENT_LIST_DIR}/System.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SystemBuilder.hpp
    ${CMAKE_CURRENT_LIST_DIR}/View.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Ecs.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Hash.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ForwardDeclarations.hpp
    ${CMAKE_CURRENT_LIST_DIR}/meta/Any.hpp
    ${CMAKE_CURRENT_LIST_DIR}/meta/Any.cpp
    ${CMAKE_CURRENT_LIST_DIR}/meta/TypeTraits.hpp
    ${CMAKE_CURRENT_LIST_DIR}/meta/FunctionTraits.hpp
    ${CMAKE_CURRENT_LIST_DIR}/meta/ComponentTraits.hpp
    ${CMAKE_CURRENT_LIST_DIR}/meta/Storage.hpp
    ${CMAKE_CURRENT_LIST_DIR}/IterationHelpers.hpp
)