function(_generate_shader_json TARGET_NAME)
    set(options "")
    set(oneValueArgs JSON)
    set(multiValueArgs SHADERS DEPENDS)
    cmake_parse_arguments(PARSE_ARGV 1 ARG "${options}" "${oneValueArgs}" "${multiValueArgs}")

    message(STATUS "JSON_FILE: ${ARG_JSON}")
    file(WRITE ${ARG_JSON} "{\n")
    file(APPEND ${ARG_JSON} "\t\"Sources\": std.uniq([")
    set(INDEX 0)
    foreach(SHADER ${ARG_SHADERS})
        get_filename_component(SHADER_ABSOLUTE_PATH "${SHADER}" ABSOLUTE)
        file(APPEND ${ARG_JSON} "\"${SHADER_ABSOLUTE_PATH}\"")
        if(NOT INDEX EQUAL 0)
            file(APPEND ${ARG_JSON} ",")
        endif()
        math(EXPR INDEX "${INDEX} + 1")
    endforeach()
    file(APPEND ${ARG_JSON} "]")

    foreach(DEPENDENCY ${ARG_DEPENDS})
        file(APPEND ${ARG_JSON} "\n\t+ (import \'${DEPENDENCY}\').Sources")
    endforeach()
    file(APPEND ${ARG_JSON} ")\n")
    file(APPEND ${ARG_JSON} "}")
endfunction()

function(target_add_shaders TARGET_NAME)
    set(options "")
    set(oneValueArgs "")
    set(multiValueArgs SHADERS)
    cmake_parse_arguments(PARSE_ARGV 1 ARG "${options}" "${oneValueArgs}" "${multiValueArgs}")

    get_target_property(LINK_LIBRARIES ${TARGET_NAME} LINK_LIBRARIES)
    set(SHADER_DEPENDENCIES)
    if(LINK_LIBRARIES AND NOT LINK_LIBRARIES STREQUAL "LINK_LIBRARIES-NOTFOUND")
        foreach(LIB ${LINK_LIBRARIES})
            get_property(SHADERS_LIST TARGET ${LIB} PROPERTY SHADERS_LIST)
            if(SHADERS_LIST)
                list(APPEND SHADER_DEPENDENCIES ${SHADERS_LIST})
            endif()
        endforeach()
    endif()


    set(JSON_FILE ${CMAKE_CURRENT_BINARY_DIR}/shaders.jsonnet)
    _generate_shader_json(${TARGET_NAME} JSON ${JSON_FILE} SHADERS ${ARG_SHADERS} DEPENDS ${SHADER_DEPENDENCIES})
    set_target_properties(${TARGET_NAME} PROPERTIES SHADERS_LIST ${JSON_FILE})
endfunction()
